# PostgreSQL configuration for local and production (Render)

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

# Local Development
development:
  <<: *default
  database: task_manager_development
  username: postgres
  password: ashutosh
  host: 127.0.0.1
  port: 5432

# Local Test Database
test:
  <<: *default
  database: task_manager_test
  username: postgres
  password: ashutosh
  host: 127.0.0.1
  port: 5432

# Render Production
production:
  primary: &primary_production
    <<: *default
    url: <%= ENV['DATABASE_URL'] || 'postgresql://online_task_db_user:vAbcHcmYDYFW5Ozzf1V8Q0ewZ9wRbDXY@dpg-d3vg1abipnbc739kfuig-a/online_task_db' %>
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

  cache:
    <<: *primary_production

  queue:
    <<: *primary_production

  cable:
    <<: *primary_production
